[en]
  weight = 2
  contentDir = "content/en"
  [en.params]
    description = "English slogan"
[de]
  weight = 1
  contentDir = "content/de"
  [de.params]
    description = "Schnell. Sicher. Stanzen."
