backend:
  name: github
  branch: master

local_backend: true

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "default" # Used in routes, e.g., /admin/collections/blog
    label: "page"
    folder: "content"
    nested: { depth: 100, summary: '{{meta.path}}'}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "headline", name: "headline", widget: "string", required: false}
      - {label: "Headline Image", name: "headline_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
