[[main]]
name = "Product"
url = "/Product"
weight = 10
[[main]]
name = "Company"
url = "/Company"
weight = 20
[[main]]
name = "Service & News"
url = "/service-news"
weight = 30

[[main]]
parent = "Product"
name = "Ausschreibungstexte"
title = "Ich bin eine Navigationsbeschreibung"
url = "/ausschreibungstexte"
weight = 10
[[main]]
parent = "Product"
name = "Anwendung"
title = "Ich bin eine Navigationsbeschreibung"
url = "/anwendung"
weight = 20
[[main]]
parent = "Product"
name = "FAQs"
title = "Ich bin eine Navigationsbeschreibung"
url = "/faqs"
weight = 30
[[main]]
parent = "Product"
name = "Technische Daten"
title = "Ich bin eine Navigationsbeschreibung"
url = "/technische-daten"
weight = 40
[[main]]
parent = "Product"
name = "Anfrage/Bestellung"
title = "Ich bin eine Navigationsbeschreibung"
url = "/anfrage-bestellung"
weight = 50
[[main]]
parent = "Product"
name = "Bezugsquellen"
title = "Ich bin eine Navigationsbeschreibung"
url = "/bezugsquellen"
weight = 60

[[main]]
parent = "Company"
name = "Datenschutz"
title = "Ich bin eine Navigationsbeschreibung"
url = "/datenschutz"
weight = 10
[[main]]
parent = "Company"
name = "Philosophie"
title = "Ich bin eine Navigationsbeschreibung"
url = "/philosophie"
weight = 20
[[main]]
parent = "Company"
name = "Sitemap"
title = "Ich bin eine Navigationsbeschreibung"
url = "/sitemap"
weight = 30
[[main]]
parent = "Company"
name = "Erfinder"
title = "Ich bin eine Navigationsbeschreibung"
url = "/erfinder"
weight = 40
[[main]]
parent = "Company"
name = "Kontakt"
title = "Ich bin eine Navigationsbeschreibung"
url = "/kontakt"
weight = 50
[[main]]
parent = "Company"
name = "Impressum"
title = "Ich bin eine Navigationsbeschreibung"
url = "/impressum"
weight = 60

[[main]]
parent = "Service & News"
name = "News"
title = "Ich bin eine Navigationsbeschreibung"
url = "/news"
weight = 10
[[main]]
parent = "Service & News"
name = "Presse"
title = "Ich bin eine Navigationsbeschreibung"
url = "/presse"
weight = 20
[[main]]
parent = "Service & News"
name = "Downloads"
title = "Ich bin eine Navigationsbeschreibung"
url = "/downloads"
weight = 30


[[action]]
name = "Buy Presssta"
url = "/produkt/bezugsquellen"




[[footer1]]
name = "Unternehmen"
url = "/unternehmen/philosophie"
weight = 10
[[footer1]]
name = "Datenschutz"
url = "/unternehmen/datenschutz"
weight = 20
[[footer1]]
name = "Impressum"
url = "/unternehmen/impressum"
weight = 30
[[footer1]]
name = "AGB"
url = "/unternehmen/agb"
weight = 40

[[footer2]]
name = "Produkt"
url = "/produkt/anwendung"
weight = 50
[[footer2]]
name = "technische Daten"
url = "/produkt/technische-daten"
weight = 60
[[footer2]]
name = "Presse"
url = "/service-news/presse"
weight = 70
[[footer2]]
name = "Bezugsquellen"
url = "/produkt/bezugsquellen"
weight = 80


[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/TODO"
weight = 10
[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/TODO"
weight = 10
[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/TODO"
weight = 10
